#!/bin/bash
set -e
set -o pipefail

rm -rf build/

TIDY_THREADS=${TIDY_THREADS:-2}

cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++
./run-clang-tidy.py -p build -j $TIDY_THREADS -allow-no-checks -config=.clang-tidy